# Generated by Django 3.0.7 on 2020-06-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='large',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='subs',
            name='small',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
