# Generated by Django 3.0.7 on 2020-06-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200610_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.PizzaStyle'),
        ),
    ]
