# Generated by Django 3.0.7 on 2020-06-11 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200610_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaToppingsClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='price0',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='price1',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='price3',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='price4',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppingsclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.PizzaToppingsClass'),
        ),
    ]
