# Generated by Django 3.0.7 on 2020-06-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200612_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='price5',
        ),
    ]
