# Generated by Django 3.0.7 on 2020-06-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200629_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='state',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
